name: Contribution Log

on:
  push:
  schedule:
    - cron: "0 */1 * * *"

jobs:
  Contribution-log:
    name: Update Scripts
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - uses: saaalik/readme-updation@main
        env:
          GITHUB_TOKEN: ${{ secret.GITHUB_TOKEN }}
        with:
          template: "SCRIPTS_TEMPLATE.md.tpl"
          writeTo: "SCRIPTS.md"

      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: Contribution Log
          branch: main
          commit_user_name: readme-scribe 🤖
          commit_user_email: actions@github.com
          commit_author: readme-scribe 🤖 <actions@github.com>
